FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Polls

Let's get you started with [API Blueprint](https://help.apiary.io/api_101/api_blueprint_tutorial)!

# Polls API Root [/]

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "questions_url": "/questions"
        }

## Data structures
### Question
- question: What's your favourite language? (string)
- published_at: `2017-06-17` (string)
- url (string)
- choices (array[Choice])

### Choice
- choice (string)
- url (string)
- votes (number)

## Group Question

## Question list [/questions]

+ Attributes(array[Question])

### Questions [GET]

+ Response 200 (application/json)

    + Attributes(array[Question])

## Question detail [/questions/{question_id}]

+ Attributes(Question)

+ Parameters
    + question_id: 1 (required, number) - ID of the Question in form of an integer

### View a question detail [GET]

+ Response 200 (application/json)

    + Attributes(Question)


### Create a new question [POST]


+ Request (application/json)

    + Attributes
        - question (Question)

+ Response 201 (application/json)

    + Attributes
        - question (Question)

### Delete a question [DELETE]

+ Response 204